
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upcgshvgqubyenuibwhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwY2dzaHZncXVieWVudWlid2hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczODY4MzIsImV4cCI6MjA1Mjk2MjgzMn0.hswm3FzWU7OwdC0hwJNYMQM51cQYRkXosg0kuMkZnAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storageKey: 'supabase_auth_token',
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false
  }
});
